modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="lootpackages"
version="1.1.1"
displayName="Loot Packages"
authors="Randoola"
description='''Ability to give players a starting package and also ability to find packages in loot!'''

[[dependencies.lootpackages]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.lootpackages]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"